name = "AltroTutorials"
uuid = "99de7b83-050b-4ddc-b2a2-204f4c2669dd"
authors = ["Brian Jackson <bjack205@gmail.com>"]
version = "0.1.0"

[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
RobotZoo = "74be38bb-dcc2-4b9e-baf3-d6373cd95f10"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
